export const supabaseUrl = 'https://jfzisybugkzcatmuphnv.supabase.co';
export const anonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmemlzeWJ1Z2t6Y2F0bXVwaG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzY1MjQ1MTAsImV4cCI6MTk5MjEwMDUxMH0.DKXTuKRwTe73xJ9kUxzXXycwuBLGFPC1VBca7zWja5U';
